name: MelyssaG
favicon: null
layout_spectrum: 0.97546
typography_spectrum: 0.3614170963410288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333132'
    - '#ffffff'
    - '#000000'
    - '#bfbdbe'
    - '#848283'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
