name: MelyssaG
favicon: null
layout_spectrum: 0.5653334704693407
typography_spectrum: 0.3614170963410288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.10057359118945897
  lightness: 0.8287936821579933
  saturation: 0.34558863565325737
  rhythmicContrast: 0.033701032400131226
purpose: []
